pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                dir('notflix') {
                    sh 'docker compose stop app mongo'
                    sh 'docker compose rm -f app mongo'
                }
            }
        }

        stage('Build') {
            steps {
                dir('notflix') {
                    sh 'docker compose build app'
                }
            }
        }

        stage('Run') {
            steps {
                dir('notflix') {
                    sh 'docker compose up -d app mongo'
                }
            }
        }
    }
}