pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                dir('notflix') {
                    sh 'docker compose stop app mongo'
                    sh 'docker compose rm -f app mongo'
                }
            }
        }

        stage('Prepare') {
            steps {
                dir('notflix') {
                    sh 'mkdir -p server client'
                    sh 'cp /var/jenkins_secrets/.env server/.env || true'
                    sh 'cp /var/jenkins_secrets/client.env client/.env.local || true'
                }
            }
        }

        stage('Build') {
            steps {
                dir('notflix') {
                    sh 'docker compose build app'
                }
            }
        }

        stage('Run') {
            steps {
                dir('notflix') {
                    sh 'docker compose up -d app mongo'
                }
            }
        }
    }
}